# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:mysql://db:3306/appdb
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  address: 0.0.0.0
  port: 8080